version: '3.4'

services:
  catalogdb:
    image: mongo
  
  basketdb:
    image: redis:alpine
  
  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest
  
  portainer:
    image: portainer/portainer-ce


  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

volumes:
  mongo_data:
  portainer_data:
